[Definition]
failregex = ^.*FATAL:  no pg_hba.conf entry for host "<HOST>", user ".*", database ".*".*$
            ^.*FATAL:  password authentication failed for user ".*" from host "<HOST>".*$
ignoreregex =
